### ISSUE TITLE
Website Font too large

### ISSUE THREAD

**Issue by whitevo** [The-Catalyst-School/website#35]
Not sure, but it feels like the website content is too much at my face.
Could we make the text a bit smaller?
![image](https://user-images.githubusercontent.com/10964567/169576324-20fb94e7-c9c2-4afc-8af7-240b696033d6.png)

Took a random google first article result and I get a way better font size where you can fit more than a few sentences in half of the screen.
![image](https://user-images.githubusercontent.com/10964567/169576500-9f56b505-8211-400c-bce9-93df0f22f8a2.png)

**Comment by coire1** [comment]
Set max size at 1920px.
